-- db zad2 

create database SuppliersParts

create table Suppliers
(
	SID char(8) primary key not null,
	NAME varchar(30) not null,
	CITY varchar(20) null
)

create table PARTS
(
	PART_ID int not null primary key identity(1 ,1),
	PART_NAME varchar(30) not null,
	COLOR varchar(10) null,
	WEIGHT decimal(6,3) null
)


create table SUPPLIERS_PARTS
(
	SID char(8),
	PART_ID int not null,
	QUANTITY int not null
	constraint PK_SUPPLIERS_PARTS_SID PRIMARY KEY (SID, PART_ID),
	CONSTRAINT FK_SUPPLIERS_PARTS FOREIGN KEY (SID)
	REFERENCES Suppliers (SID)
	ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT FK_SUPPLIERS_PARTS_PART FOREIGN KEY (PART_ID)
	REFERENCES PARTS (PART_ID)
)

-- dobavqne zapisi v shemata v posledovatelnost pravilna spored men

insert into Suppliers(SID,NAME, CITY)
values('BMWMU','bmw','Munchen')

insert into Suppliers
values('FERRIT','FERRARI','ITALIA')

INSERT INTO PARTS (PART_ID,PART_NAME,COLOR,WEIGHT)
VALUES (1,'ENGINE','GREY',200)

INSERT INTO PARTS (PART_ID,PART_NAME,COLOR,WEIGHT)
VALUES (2,'GEARBOX','GREY',80)

INSERT INTO SUPPLIERS_PARTS 
VALUES ('BMWMU', 1, 40)

INSERT INTO SUPPLIERS_PARTS 
VALUES ('FERRIT', 2, 60)

-- c) IZTRIVANE NA VSI4KI DETAILI S TEGLO POD 50 
DELETE FROM PARTS
WHERE WEIGHT < 50

-- d)ZAQVKA KOQTO VRU6TA IME I CVQT NA VSI4KI DETAILI
SELECT PART_NAME,COLOR 
FROM PARTS 

-- E) ZAQVKA KOQTO VRU6TA IMENATA NA VSI4KI DETAILI KOITO SA V KOLI4ESTWO PO GOLQMO OT 100

SELECT PART_NAME 
FROM PARTS P, SUPPLIERS_PARTS SP
WHERE P.PART_ID = SP.PART_ID
AND QUANTITY > 100

-- F) ZAQVKA KOQTO VRU6TA OB6TOTO DOSTAVENO KOLI4ESTVO ZA OPREDELENA 4AST

SELECT QUANTITY
FROM PARTS P, SUPPLIERS_PARTS SP
WHERE P.PART_ID = SP.PART_ID
AND PART_NAME = 'ENGINE'

-- g) ZAQVKA KOQTO VRU6TA IME NA DOSTAV4IK I DOSTAVKI KOITO 
--E NAPRAWIL ZA EDNA OPREDELENA 4AST

SELECT NAME, COUNT(SP.SID) AS BROI_DOSTAVKI
FROM SUPPLIERS S, SUPPLIERS_PARTS SP
WHERE S.SID = SP.SID
AND  PART_ID = 2
GROUP BY S.SID, NAME
-- H) DA SE RAZ6IRI PREDNATA ZAQVKA KATO SE IZVEDAT SAMO TEZI DOSTAV4ICI KOITO 
-- SA NAPRAVILI NAD 3 DOSTAVKI

SELECT NAME, COUNT(SP.SID) AS BROI_DOSTAVKI
FROM SUPPLIERS S, SUPPLIERS_PARTS SP
WHERE S.SID = SP.SID
AND  PART_ID = 2
AND  COUNT(SP.SID) > 3 -- NE STAVA
GROUP BY S.SID, NAME

-- I) ZAQVKA KOQTO VRU6TA KATO REZULTAT NAIMENUVANIE NA DETAIL,
-- CVQT, TEGLO, DOSTAVENO KOLI4ESTVO ZA NAI TEJKIQ I LEKIQ DETAIL

SELECT top 1 WITH TIES PART_NAME, COLOR, WEIGHT, QUANTITY 
FROM PARTS P, SUPPLIERS_PARTS SP
WHERE P.PART_ID = SP.PART_ID
ORDER BY WEIGHT ASC

-- k) ZAQWKA KOQTO VRU6TA KATO REZULTAT IME
--NA DETAIL CVQT I OB6TO TEGLO NA DOSTAVKA

SELECT PART_NAME, COLOR,  COUNT(P.WEIGHT*SP.QUANTITY)
FROM PARTS P , SUPPLIERS_PARTS SP
WHERE P.PART_ID = SP.PART_ID
GROUP BY PART_NAME, P.PART_ID, COLOR


-- L) suzdavane na izgled koito sudurja informaciq za 
-- dostav4ika , broq na dostavkite i ob6to teglo na dostavka

CREATE VIEW SUPPLIER_ORDERS_WEIGHT
AS
SELECT NAME,COUNT(SP.SID) AS ORD_COUNT,  COUNT(P.WEIGHT*SP.QUANTITY) AS ORD_WEIGHT
FROM SUPPLIERS S, SUPPLIERS_PARTS SP, PARTS P
WHERE S.SID = SP.SID
AND SP.PART_ID = P.PART_ID
GROUP BY NAME, S.SID

-- M) suzdavane na procedura koqto za podaden kato vhoden parametyr
-- identifikator na detail izvejda imena na dostav4ika, koito 
-- q e dostavil, imento na detaila i koli4estwoto.

CREATE PROCEDURE INS_ID_SUP_NAME @PART_ID INT
AS
SELECT  NAME, PART_NAME, QUANTITY
FROM SUPPLIERS S, SUPPLIERS_PARTS SP, PARTS P
WHERE S.SID = SP.SID
AND SP.PART_ID = P.PART_ID
AND P.PART_ID = @PART_ID

EXEC  INS_ID_SUP_NAME @PART_ID = 1
