CREATE TABLE COUNTRIES 
(
 COUNTRY_ID CHAR(2) NOT NULL,
 NAME VARCHAR(40) NOT NULL,
 REGION_ID SMALLINT NULL,
 CONSTRAINT PK_COUNTRY PRIMARY KEY (COUNTRY_ID),
 CONSTRAINT FK_COUNTRIES_REGIONS FOREIGN KEY (REGION_ID)
 REFERENCES REGIONS (REGION_ID)
)

ALTER TABLE COUNTIRES
DROP CONSTRAINT FK_COUNTRIES_REGIONS;

ALTER TABLE COUNTRIES ADD CONSTRAINT FK_COUNTRIES_REGIONS FOREIGN KEY (REGION_ID)
 REFERENCES REGIONS (REGION_ID)
 
DROP TABLE COUNTRIES

CREATE TABLE CUSTOMERS 
(
 CUSTOMER_ID NUMERIC(6) NOT NULL,
 COUNTRY_ID CHAR(2) NOT NULL,
 FNAME VARCHAR(20) NOT NULL,
 LNAME VARCHAR(20) NOT NULL,
 ADDRESS TEXT NULL,
 EMAIL VARCHAR(30) NULL,
 GENDER CHAR(1) NULL DEFAULT 'M'
 CONSTRAINT CUST_GENDER CHECK (GENDER IS NULL OR (GENDER IN ('M','F'))),
 CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
)


DROP TABLE CUSTOMERS

ALTER TABLE CUSTOMERS
 ADD CONSTRAINT FK_CUSTOMER_COUNTRIES FOREIGN KEY (COUNTRY_ID)
 REFERENCES COUNTRIES (COUNTRY_ID)


 CREATE TABLE JOBS 
(
 JOB_ID VARCHAR(10) NOT NULL PRIMARY KEY,
 JOB_TITLE VARCHAR(35) NOT NULL,
 MIN_SALARY NUMERIC(6) NULL,
 MAX_SALARY NUMERIC(6) NULL
)

CREATE TABLE EMPLOYEES 
(
 EMPLOYEE_ID INT NOT NULL,
 FNAME VARCHAR(20) NOT NULL,
 LNAME VARCHAR(25) NOT NULL,
 EMAIL VARCHAR(40) NOT NULL,
 PHONE VARCHAR(20) NULL,
 HIRE_DATE DATETIME NOT NULL,
 SALARY NUMERIC(8,2) NOT NULL
 CONSTRAINT SALARY_CHECK CHECK (SALARY > 0),
 JOB_ID VARCHAR(10) NOT NULL,
 MANAGER_ID INT NULL,
 DEPARTMENT_ID INT NULL,
 CONSTRAINT PK_EMPLOYEES PRIMARY KEY (EMPLOYEE_ID),
 CONSTRAINT UK_EMAIL UNIQUE (EMAIL),
 CONSTRAINT FK_EMPLOYEE_JOBS FOREIGN KEY (JOB_ID) REFERENCES JOBS (JOB_ID),
 CONSTRAINT FK_EMPLOYEE_MANAGERS FOREIGN KEY (MANAGER_ID)
 REFERENCES EMPLOYEES (EMPLOYEE_ID)
)


CREATE TABLE DEPARTMENTS
(
 DEPARTMENT_ID INT NOT NULL,
 NAME VARCHAR(30) NOT NULL,
 MANAGER_ID INT NULL,
 COUNTRY_ID CHAR(2) NOT NULL,
 CITY VARCHAR(30) NOT NULL,
 STATE VARCHAR(25) NULL,
 ADDRESS VARCHAR(40) NULL,
 POSTAL_CODE VARCHAR(12) NULL,
 CONSTRAINT PK_DEPT PRIMARY KEY (DEPARTMENT_ID),
 CONSTRAINT FK_DEPT_MGR FOREIGN KEY (MANAGER_ID)
 REFERENCES EMPLOYEES (EMPLOYEE_ID),
 CONSTRAINT FK_DEPT_COUNTRIES FOREIGN KEY (COUNTRY_ID)
 REFERENCES COUNTRIES (COUNTRY_ID)
)
ALTER TABLE EMPLOYEES
ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENTS FOREIGN KEY (DEPARTMENT_ID) 
REFERENCES DEPARTMENTS


CREATE TABLE ORDERS 
(
 ORDER_ID INT NOT NULL PRIMARY KEY,
 ORDER_DATE DATETIME NOT NULL,
 CUSTOMER_ID NUMERIC(6) NOT NULL FOREIGN KEY REFERENCES CUSTOMERS,
 EMPLOYEE_ID INT NOT NULL FOREIGN KEY REFERENCES EMPLOYEES,
 SHIP_ADDRESS VARCHAR(150) NULL
)


CREATE TABLE PRODUCTS 
(
 PRODUCT_ID INT NOT NULL PRIMARY KEY,
 NAME VARCHAR(70) NOT NULL,
 PRICE NUMERIC(8,2) NOT NULL,
 DESCR VARCHAR(2000) NULL,
)

CREATE TABLE ORDER_ITEMS
(
 ORDER_ID INT NOT NULL,
 PRODUCT_ID INTEGER NOT NULL,
 UNIT_PRICE NUMERIC(8,2) NOT NULL,
 QUANTITY NUMERIC(8) NOT NULL,
 CONSTRAINT PK_ORDER_ITEMS PRIMARY KEY (ORDER_ID, PRODUCT_ID),
 CONSTRAINT FK_ORD_ITEM_ORDERS FOREIGN KEY (ORDER_ID)
 REFERENCES ORDERS (ORDER_ID)
 ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT FK_ORD_ITEM_PRODUCTS FOREIGN KEY (PRODUCT_ID)
 REFERENCES PRODUCTS (PRODUCT_ID)
)


INSERT INTO REGIONS (NAME)
VALUES ('Източна Европа');

SELECT * FROM REGIONS

DELETE FROM REGIONS

INSERT INTO COUNTRIES (COUNTRY_ID, NAME, REGION_ID)
VALUES ('BG', 'България', 1);

DELETE FROM COUNTRIES
SELECT * FROM COUNTRIES


INSERT CUSTOMERS(CUSTOMER_ID,COUNTRY_ID,FNAME,LNAME,ADDRESS,EMAIL,GENDER)
VALUES (1001, 'BG', 'Георги', 'Генев', 'бул. България 100, Пловдив',
'ggenev@gmail.com', 'M');

DELETE FROM CUSTOMERS
SELECT * FROM CUSTOMERS

INSERT INTO JOBS (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY)
VALUES ('SA_REP', 'Търговски представител', 9000, 17000);

DELETE FROM JOBS
SELECT * FROM JOBS

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, NAME, COUNTRY_ID, CITY, STATE, 
ADDRESS, POSTAL_CODE)
VALUES (80, 'Продажби', 'BG', 'Пловдив', 'Пловдив', 'бул. Марица 10', '4000')

DELETE FROM DEPARTMENTS
SELECT * FROM DEPARTMENTS

INSERT INTO EMPLOYEES(EMPLOYEE_ID, FNAME, LNAME, EMAIL, PHONE, HIRE_DATE,
JOB_ID, SALARY, DEPARTMENT_ID)
VALUES (1501, 'Петър', 'Тодоров', 'petert@trade_company.com', '0899332013',
CONVERT(DATE, '30-01-2017', 105), 'SA_REP', 19000, 80);

DELETE FROM EMPLOYEES
SELECT * FROM EMPLOYEES

INSERT INTO PRODUCTS(PRODUCT_ID, NAME, DESCR, PRICE)
VALUES (20001, 'Смартфон Samsung Galaxy S10e', 'Смартфон Samsung Galaxy S10e, 
Dual SIM, 128GB, 6GB RAM, 4G, Black.', 1400);

DELETE FROM PRODUCTS
SELECT * FROM PRODUCTS

INSERT ORDERS(ORDER_ID, CUSTOMER_ID, EMPLOYEE_ID, SHIP_ADDRESS, ORDER_DATE)
VALUES (1, 1001, 1501, 'бул. България 140, Пловдив', CONVERT(DATETIME, '13-
07-2010 10:30', 105));

DELETE FROM ORDERS
SELECT * FROM ORDERS

INSERT INTO ORDER_ITEMS(ORDER_ID, PRODUCT_ID, UNIT_PRICE, QUANTITY)
VALUES (1, 20001, 1400, 2);

DELETE FROM ORDER_ITEMS
SELECT * FROM ORDER_ITEMS

UPDATE EMPLOYEES
SET SALARY = 20200
WHERE EMPLOYEE_ID = 1501

DELETE FROM ORDERS
WHERE ORDER_ID = 1

-- упражнение страница >=60

SELECT *
FROM PRODUCTS 
WHERE PRICE > 2000
ORDER BY PRICE;

SELECT COUNT(EMPLOYEE_ID)
FROM EMPLOYEES;


SELECT DEPARTMENT_ID, COUNT(EMPLOYEE_ID) AS  EMP_COUNT
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
